version: "3.7"

services:
  app:
    build:
      args:
        user: tbnb
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: tbnb-test
    container_name: tbnb-test
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - tbnb-test-net
  db:
    image: mysql:5.7
    container_name: tbnb-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - 3306:3306
    networks:
      - tbnb-test-net
  nginx:
    image:  nginx:alpine
    container_name: tbnb-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - tbnb-test-net


networks:
  tbnb-test-net:
      driver: bridge
