<?php

namespace App\Models;

use App\Observers\ProductObserver;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @mixin Builder
 */
class Product extends Model
{
    use HasFactory;

    protected $fillable = ["name", "price", "quantity"];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Product::observe(ProductObserver::class);
    }
}
